from enum import Enum

class Thumbnail:
    def __init__(self, data: dict):
        # ------ Error Info ------
        self.request_id: str | None = data.get("requestId")
        self.error_code: int | None = data.get("errorCode")
        self.error_message: str | None = data.get("errorMessage")
        
        # ------ Thumbnail Info ------
        self.target_id: int = data.get("targetId")
        self.state: str = data.get("state")
        self.image_url: str = data.get("imageUrl")
        self.version: str = data.get("version")

    def __repr__(self):
        return f"<Thumbnail target_id={self.target_id} state={self.state}>"


class ThumbnailMetadata:
    def __init__(self, data: dict):
        self.cache_enabled: bool = data.get("isWebappUseCacheEnabled", False)
        self.cache_expiration: str | None = data.get("webappCacheExpirationTimspan")


class ThumbnailBatchTypes(Enum):
    AVATAR = "Avatar"
    AVATAR_HEAD_SHOT = "AvatarHeadShot"
    GAME_ICON = "GameIcon"
    BADGE_ICON = "BadgeIcon"
    GAME_THUMBNAIL = "GameThumbnail"
    GAME_PASS = "GamePass"
    ASSET = "Asset"
    BUNDLE_THUMBNAIL = "BundleThumbnail"
    OUTFIT = "Outfit"
    GROUP_ICON = "GroupIcon"
    DEVELOPER_PRODUCT = "DeveloperProduct"
    AUTO_GENERATED_ASSET = "AutoGeneratedAsset"
    AVATAR_BUST = "AvatarBust"
    PLACE_ICON = "PlaceIcon"
    AUTO_GENERATED_GAME_ICON = "AutoGeneratedGameIcon"
    FORCE_AUTO_GENERATED_GAME_ICON = "ForceAutoGeneratedGameIcon"
    LOOK = "Look"
    CREATOR_CONTEXT_ASSET = "CreatorContextAsset"
    SCREENSHOT = "Screenshot"


class ThumbnailBatch:
    def __init__(self):
         self._batches: list[dict] = []

    def add(
        self,
        request_id: str,
        target_id: int,
        type: ThumbnailBatchTypes,

        token: str = "",
        alias: str = "",
        size: str = "30x30",
        format: str = "Png",
        is_circular: bool = False,
        access_context: str = "",
        head_shape: str = ""
    ):
        self._batches.append(
            {
                "requestId": request_id,
                "targetId": target_id,
                "token": token,
                "alias": alias,
                "type": type.value,
                "size": size,
                "format": format,
                "isCircular": is_circular,
                "accessContext": access_context,
                "headShape": head_shape
            }
        )

    def to_dict(self):
        return self._batches