from enum import Enum

class Thumbnail:
    def __init__(self, data: dict):
        # ------ Error Info ------
        self.request_id: str | None = data.get("requestId")
        self.error_code: int | None = data.get("errorCode")
        self.error_message: str | None = data.get("errorMessage")
        
        # ------ Thumbnail Info ------
        self.target_id: int = data.get("targetId")
        self.state: str = data.get("state")
        self.image_url: str = data.get("imageUrl")
        self.version: str = data.get("version")

    def __repr__(self):
        return f"<Thumbnail target_id={self.target_id} state={self.state}>"


class ThumbnailMetadata:
    def __init__(self, data: dict):
        self.cache_enabled: bool = data.get("isWebappUseCacheEnabled", False)
        self.cache_expiration: str | None = data.get("webappCacheExpirationTimspan")


class ThumbnailBatchTypes(Enum):
    AVATAR = "Avatar"
    AVATAR_HEAD_SHOT = "AvatarHeadShot"
    GAME_ICON = "GameIcon"
    BADGE_ICON = "BadgeIcon"
    GAME_THUMBNAIL = "GameThumbnail"
    GAME_PASS = "GamePass"
    ASSET = "Asset"
    BUNDLE_THUMBNAIL = "BundleThumbnail"
    OUTFIT = "Outfit"
    GROUP_ICON = "GroupIcon"
    DEVELOPER_PRODUCT = "DeveloperProduct"
    AUTO_GENERATED_ASSET = "AutoGeneratedAsset"
    AVATAR_BUST = "AvatarBust"
    PLACE_ICON = "PlaceIcon"
    AUTO_GENERATED_GAME_ICON = "AutoGeneratedGameIcon"
    FORCE_AUTO_GENERATED_GAME_ICON = "ForceAutoGeneratedGameIcon"
    LOOK = "Look"
    CREATOR_CONTEXT_ASSET = "CreatorContextAsset"
    SCREENSHOT = "Screenshot"


class ThumbnailBatch:
    def __init__(
        self,
        request_id: str,
        target_id: int,
        type: ThumbnailBatchTypes,
        
        token: str = "",
        alias: str = "",,
        size: str = "30x30",
        format: str = "Png",
        is_circular: bool = False,
        access_context: str = "",
        head_shape: str = ""
        
    ):
         self.__request_id = request_id
         self.__target_id = target_id
         self.__token = token
         self.__alias = alias
         self.__type = type.value
         self.__size = size
         self.__format = format
         self.__is_circular = is_circular
         self.__access_context = access_context
         self.__head_shape = head_shape

    def to_dict(self):
        return {
            "requestId": self.__request_id,
            "targetId": self.__target_id,
            "token": self.__token,
            "alias": self.__alias,
            "type": self.__type,
            "size": self.__size,
            "format": self.__format,
            "isCircular": self.__is_circular,
            "accessContext": self.__access_context,
            "headShape": self.__head_shape
        }