from enum import Enum

class ReturnPolicy(Enum):
    PlaceHolder = "PlaceHolder"
    ForcePlaceHolder = "ForcePlaceHolder"
    AutoGenerated = "AutoGenerated"
    ForceAutoGenerated = "ForceAutoGenerated"